spring:
  application:
    name: imagine_book_store

server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    whitelabel:
      enabled: 'false'
    include-stacktrace: 'never'

security:
  jwt:
    token:
      security-key: ${JWT_SECRET}